
[build]
  # Directory to publish (relative to root of your repo)
  publish = "dist"
  # Force install devDependencies before build to ensure Vite is available
  command = "npm install --include=dev && npm run build"

[build.environment]
  NODE_VERSION = "20"
  NPM_VERSION = "10"
  NODE_ENV = "development"
  
# Context-specific settings
[context.production]
  environment = { NODE_ENV = "production", REACT_APP_ENVIRONMENT = "production" }

[context.deploy-preview]
  environment = { NODE_ENV = "production", REACT_APP_ENVIRONMENT = "preview" }

[context.branch-deploy]
  environment = { NODE_ENV = "production", REACT_APP_ENVIRONMENT = "staging" }
  
# Using local plugin path (relative to project root)
[[plugins]]
  package = "./netlify/plugins"

# API proxy redirects - handle CORS issues
[[redirects]]
  from = "/api/aws/*"
  to = "https://4xituwvy3i.execute-api.us-east-1.amazonaws.com/dev/:splat"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*", Access-Control-Allow-Methods = "GET,POST,PUT,DELETE,OPTIONS", Access-Control-Allow-Headers = "Content-Type,Authorization"}

# Redirects and headers for Single Page Applications
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Add security headers for all pages
[[headers]]
  for = "/*"
    [headers.values]
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; connect-src 'self' https://*.netlify.app https://api.fraudlens.com https://4xituwvy3i.execute-api.us-east-1.amazonaws.com;"
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
    
# Add cache control for assets
[[headers]]
  for = "*.js"
    [headers.values]
    Cache-Control = "public, max-age=31536000"
[[headers]]
  for = "*.css"
    [headers.values]
    Cache-Control = "public, max-age=31536000"
[[headers]]
  for = "*.png"
    [headers.values]
    Cache-Control = "public, max-age=31536000"
[[headers]]
  for = "*.jpg"
    [headers.values]
    Cache-Control = "public, max-age=31536000"
[[headers]]
  for = "*.svg"
    [headers.values]
    Cache-Control = "public, max-age=31536000"
